# Generated by Django 3.1.3 on 2020-12-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sites', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_sites.customsite'),
        ),
        migrations.AlterField(
            model_name='video',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_sites.customsite'),
        ),
    ]
