# Generated by Django 3.1.3 on 2020-12-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sites', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='site',
            field=models.ManyToManyField(related_name='get_site', to='custom_sites.CustomSite'),
        ),
    ]
