# Generated by Django 3.1.3 on 2020-12-03 10:38

from django.db import migrations
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('on_site', user.managers.CustomUserSiteManager()),
            ],
        ),
    ]
