export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const FETCH_IMAGES = 'FETCH_IMAGES'
export const CREATE_IMAGE = 'CREATE_IMAGE'
export const DELETE_IMAGE = 'DELETE_IMAGE'

export const FETCH_VIDEOS = 'FETCH_VIDEOS'
export const CREATE_VIDEO = 'CREATE_VIDEO'
export const DELETE_VIDEO = 'DELETE_VIDEO'
